### ISSUE TITLE
Mathquill formula authoring does not work in Safari browser

### ISSUE THREAD

**Issue by anuragd7** [c-w/mathquill4quill#1]
Hi
Thanks for sharing this module. It works perfectly in Chrome, however, does not appear to work in Safari (including the live demo you have shared). Any thoughts on how to fix this.

Thanks

**Comment by c-w** [comment]
Linking the solution you came up with for posteriority: https://github.com/quilljs/quill/issues/802#issuecomment-493690983

If there's any way to integrate this fix cleanly into the extension, I'd also welcome a pull request!

**Comment by c-w** [comment]
A fix for this has now been merged. Thanks to @boomanaiden154 for the pull request!
