### ISSUE TITLE
Hi, is there a way I can trigger the function button with keyboard input? 

### ISSUE THREAD

**Issue by ultrainstinct1987** [c-w/mathquill4quill#100]
Is there a way where I can trigger a function key by pressing a certain keystroke? 
ie. press shift + M will trigger the maths input button

**Comment by c-w** [comment]
If you’re looking to trigger toolbar functionality via keyboard shortcuts, that would be a request for the upstream quill project (e.g. https://github.com/quilljs/quill/issues/1972) as mathquill4quill is only scoped to math rendering.
