### ISSUE TITLE
Edit existing formula

### ISSUE THREAD

**Issue by roobox** [c-w/mathquill4quill#108]
Hi guys,

is there any way, even a dirty hack to allow users to edit existing formulas? Could I somehow access the formula module, open the popup and paste there "manually" the content of the data-value of the ql-formula-span?

**Comment by c-w** [comment]
Thanks for reaching out. This use-case has come up a few times before but really it's something that needs to first be implemented in upstream quill. See https://github.com/c-w/mathquill4quill/issues/17 for more details.
