### ISSUE TITLE
Nextjs / 404 This page could not be found.

### ISSUE THREAD

**Issue by LifeAsDev** [c-w/mathquill4quill#109]
I clone the Nextjs app and install dependencies, then npm run start, go to localhost:3000 and show 404 This page could not be found.

**Comment by c-w** [comment]
Try going to http://localhost:3000/mathquill4quill/nextjs (as per [the basePath config](https://github.com/c-w/mathquill4quill/blob/e78be296c60f4aa528d329eac56c197043775759/nextjs/next.config.js#L3))
