### ISSUE TITLE
[Visual math buttons] appear in all the popups, not only formula popup

### ISSUE THREAD

**Issue by amaslakov** [c-w/mathquill4quill#14]
When adding a link or a video:
https://codesandbox.io/s/react-quill-o1k11

**Comment by c-w** [comment]
Thanks for reporting this. A fix has been published in [v0.1.2](https://github.com/c-w/mathquill4quill/releases/tag/v0.1.2).

**Comment by c-w** [comment]
While investigating this, I noticed that the latex styling was also leaking to other popups. A fix for this has been published in [v0.1.3](https://github.com/c-w/mathquill4quill/releases/tag/v0.1.3).
