### ISSUE TITLE
Add package to NPM

### ISSUE THREAD

**Issue by itsUndefined** [c-w/mathquill4quill#16]
It would be very useful for those who use quill by bundling it themselves to have this package published on NPM.

**Comment by c-w** [comment]
Thanks for reaching out @itsUndefined. This is a great suggestion and is already supported by our deployment scripts so it should be fairly easy to implement.

**Comment by boomanaiden154** [comment]
@c-w It doesn't look like anything needs to be modified in `mathquill4quill.js` in order for it to be used with webpack or browserify.

**Comment by itsUndefined** [comment]
I can confirm it builds fine. It's just for convenience on getting newer versions.
