### ISSUE TITLE
Support for editing formula

### ISSUE THREAD

**Issue by itsUndefined** [c-w/mathquill4quill#17]
It would be awesome if clicking anywhere in a formula, the popup to insert a formula would open up to update the clicked formula. A small error in a huge formula could be a pain for a user to fix.

**Comment by boomanaiden154** [comment]
This is more of an issue with [quill](https://github.com/quilljs/quill) than it is with this project. Until Quill implements this, full support cannot be implemented in this project.

**Comment by anisabboud** [comment]
Related: https://github.com/quilljs/quill/issues/801, https://github.com/quilljs/quill/pull/2147.
