### ISSUE TITLE
Publish 0.1.4 on NPM

### ISSUE THREAD

**Issue by itsUndefined** [c-w/mathquill4quill#23]
Title is self explanatory. We need the bug fixes that are on 0.1.4 and it would be really helpful to have them uploaded on NPM.

**Comment by c-w** [comment]
I saw some odd behavior with NPM related to `npm publish` claiming that `0.1.4` had already been published so I bumped the version up to [1.0.0](https://www.npmjs.com/package/mathquill4quill/v/1.0.0); NPM now is back in sync with the Github releases.
