### ISSUE TITLE
Cannot edit Latex syntax that is not supported by MathQuill

### ISSUE THREAD

**Issue by ninbit** [c-w/mathquill4quill#28]
Hi, visualizing the formulas with buttons is very lovely feature. I want to use it but it supports limited formulas. So I tried to add buttons for non-supported formulas for just editing the latex syntax in the formula input but the latex syntax can not be edited there.

For example, I added `["\\xleftarrow[x]{y}", "\\xleftarrow[x]{y}"]` to the buttons in order to change x and y in the formula input but the cursor just goes to the begining or end, not to x or y. So, how can it be edited?

**Comment by c-w** [comment]
Given that this project is built on-top of MathQuill, we can only render the subset of LaTeX that is implemented in MathQuill ([list of supported commands](https://github.com/mathquill/mathquill/blob/248691db23a76c048c0db660957000dfe2ca4048/src/commands/math/commands.js)). If you need support of additional operators, I'd recommend reaching out to the MathQuill project directly.
