### ISSUE TITLE
Feature request: Preserve formula content when tooltip is closed

### ISSUE THREAD

**Issue by anisabboud** [c-w/mathquill4quill#33]
Thank you for this wrapper!

I've noticed that the formula content gets deleted/reset when the tooltip is closed and then re-opened:
![Formula is deleted when tooltip is closed](https://user-images.githubusercontent.com/5672108/73282818-db97a780-41fa-11ea-8e27-a98983a25230.gif)

Is it possible to preserve the content so that users would not lose the formula if they accidentally clicked outside the tooltip? Thanks a lot!

**Comment by c-w** [comment]
Thanks for reaching out. This feature has now been released in [v1.0.2](https://github.com/c-w/mathquill4quill/releases/tag/v1.0.2).

**Comment by anisabboud** [comment]
That was fast, thanks a lot!
