### ISSUE TITLE
Add ability to pass MathQuill Configuration.

### ISSUE THREAD

**Issue by wilkinsonjack1993** [c-w/mathquill4quill#37]
I am trying to add some configuration to MathQuill as described here: http://docs.mathquill.com/en/latest/Config/

It would be nice to open up the API to allow for adding MathQuill configuration that will be spread into the object that contains handlers in `mathquill4quill.js`: 
 
<img width="610" alt="Screenshot 2020-02-18 at 18 05 42" src="https://user-images.githubusercontent.com/28815690/74764465-ab7f7980-5279-11ea-8d14-a0f4a8acb010.png">

If there is another way of doing this could you point me in the right direction please? If not I can put a PR in needed.

**Comment by boomanaiden154** [comment]
In PR #38 there is an option called `mathQuillConfig` where you can pass in the options that you wish to use with MathQuill.

**Comment by c-w** [comment]
A fix for this has been released in [v2.0.1](https://github.com/c-w/mathquill4quill/releases/tag/v2.0.1).
