### ISSUE TITLE
Inconsistent Input Field Behavior

### ISSUE THREAD

**Issue by purnomosejati** [c-w/mathquill4quill#46]
Hi Wolff,

Thank you for your answer of issue #45 .

Anyway, I just found something strange on mathquill4quill demo here

https://justamouse.com/mathquill4quill/

I clicked video upload icon and input field appears. Then I clicked formula icon and back again to click video upload but input field appears different to previous one.

Please see following picture.

![mathquill4quill](https://user-images.githubusercontent.com/6489443/77384247-7bb31c80-6db7-11ea-9367-e3d0ab64cbf5.png)

Many thanks

**Comment by purnomosejati** [comment]
Once again,

I tried to edit formula using mobile phone (chrome browser) here

https://justamouse.com/mathquill4quill/

and I can't input number using keyboard although using number from both qwerty and keypad mode.

**Comment by c-w** [comment]
Thanks for reporting these bugs! To simplify tracking, I split the second one (mobile input) out into its own issue: https://github.com/c-w/mathquill4quill/issues/47.

**Comment by c-w** [comment]
The input field disappearing from the video tooltip is a regression introduced in https://github.com/c-w/mathquill4quill/pull/36 when we moved from inline styles to CSS classes. When we open the formula tooltip, we add some classes to hide the input. These classes need to be removed when the tooltip closes.

**Comment by c-w** [comment]
A fix for this has been released in [v2.1.1](https://github.com/c-w/mathquill4quill/releases/tag/v2.1.1).
