### ISSUE TITLE
Input not working on mobile

### ISSUE THREAD

**Issue by c-w** [c-w/mathquill4quill#47]
From @purnomosejati:

> I tried to edit formula using mobile phone (chrome browser) here
>
> https://justamouse.com/mathquill4quill/
>
> and I can't input number using keyboard although using number from both qwerty and keypad mode.

**Comment by c-w** [comment]
Confirmed the behavior on Chrome Android: nothing can be entered into the MathQuill input box.

On Firefox Android the behavior is also somewhat broken: initially only numbers can be entered into the input box but once the first number is entered, all symbols can be entered.

**Comment by c-w** [comment]
It looks like this is an incompatibility in MathQuill itself (see lots of [issues relating to mobile support on the upstream Github repository](https://github.com/mathquill/mathquill/issues?q=is%3Aissue+is%3Aopen+mobile)).

The latest published version of MathQuill is 4 years old and doesn't include a number of fixes for improved mobile support (see lots of [issues regarding a new release on the upstream Github repository](https://github.com/mathquill/mathquill/issues?q=is%3Aissue+is%3Aopen+release)).

There is a [fork of MathQuill on NPM](https://www.npmjs.com/package/@edtr-io/mathquill) whose last release is only 8 months ago. Switching to this fork for the demo page may fix some of the mobile issues.

**Comment by c-w** [comment]
A fix for this has been merged and the demo page has been updated. @purnomosejati feel free to reopen this issue if you're still experiencing the behavior.

**Comment by anisabboud** [comment]
Hi Clemens, I'm still seeing this issue on the official demo https://justamouse.com/mathquill4quill/.
(Open demo on Android Chrome → click _fx_ → try to type a formula - nothing shows up.)

**Comment by c-w** [comment]
@anisabboud I just pushed a fix for this and verified the demo on Android. Let me know if you have any additional issues and feel free to reopen.
