### ISSUE TITLE
Create initial release

### ISSUE THREAD

**Issue by boomanaiden154** [c-w/mathquill4quill#5]
I think it would be useful to create a github release containing of the current version of the repository with the `mathquill4quill.js` file, and the minified version version `mathquill4quill.min.js` This would allow for people using this library to easily be able to download it and include it in their webapps.

**Comment by c-w** [comment]
Good point! Added [release scripts](https://github.com/c-w/mathquill4quill/commit/65d6352aece89468a87ff9d2e53a822866c94eb3) and created [v0.0.1](https://github.com/c-w/mathquill4quill/releases/tag/v0.0.1).
