### ISSUE TITLE
\begin{matrix} is unable to be rendered

### ISSUE THREAD

**Issue by purnomosejati** [c-w/mathquill4quill#52]
Hi Wolff,

I saw that Mathquill4quill uses Katex instead of Mathjax.
And there are a lot of Latex functions that can be rendered using Katex as shown in documentation here
https://katex.org/docs/supported.html
However, Mathquil4quill can not rendered this

 **\begin{matrix} a & b \\ c & d \end{matrix}**

My question, is that the limitation or bug?

Many thanks

**Comment by c-w** [comment]
Rendering the formulae on-the-fly while typing is handled by [MathQuill](https://github.com/mathquill/mathquill) which doesn't currently support matrices or other `\begin` environments ([see several open issues on the MathQuill repository](https://github.com/mathquill/mathquill/issues?q=is%3Aissue+is%3Aopen+matrix)).

There are some forks on the MathQuill repository which implement matrix support (e.g. [see learnosity/matrix-minimal](https://github.com/Learnosity/mathquill/tree/matrix-minimal), so if you need support for matrices in mathquill4quill right now before the feature is officially added to MathQuill, I'd recommend to plug-in a version of MathQuill compiled from one of those forks:

```js
// import a forked version of MathQuill
const MathQuill = require('path/to/mathquill/compiled/from/fork');

// inject the forked version of MathQuill into the library
const enableMathQuillFormulaAuthoring = mathquill4quill({ MathQuill });

// now use the library as normal
enableMathQuillFormulaAuthoring(/* ... your mathquill4quill configuration here */);
```
