### ISSUE TITLE
how to hide "operators button" checkbox but its function normally "on"?

### ISSUE THREAD

**Issue by purnomosejati** [c-w/mathquill4quill#53]
Hi Wolff

When I click operators button checkbox, It triggers page refresh and destroy some php data from $_POST. 

The formula template is a good feature but the checkbox sometimes mess entire page function.

Please let me know if the operator button checkbox can be hide and the formula template is started from the beginning.

Thanks

Best Regards

**Comment by c-w** [comment]
Could you clarify where the PHP POST data comes from? The [demo page](https://justamouse.com/mathquill4quill/) is only intended for testing of this repository, not for integration into other systems. If you want to integrate mathquill4quill into another system, I suggest you follow the [usage example](https://github.com/c-w/mathquill4quill#usage-example).

**Comment by c-w** [comment]
Closing this since I haven't heard from you in a while. Feel free to re-open if you have any additional questions or concerns. Thanks!
