### ISSUE TITLE
Does not allow editing a formula / selection

### ISSUE THREAD

**Issue by uadarsh** [c-w/mathquill4quill#54]
If I enter formula through the quill interface (toolbar -> fx), and later go back to edit it I have to enter the formula from scratch. Ideally the already entered formula should be populated in the formula input box which may then be edited.
 Not sure whether to call this a bug or a feature-request. Is this non-trivial to fix/support?

**Comment by c-w** [comment]
Thanks for reaching out. I agree that editing formulae would be amazing. However, this is something that the upstream Quill project must implement first before we can wrap it in mathquill4quill (which really just is a convenience/rendering layer to enable users to see LaTeX as they type). See https://github.com/c-w/mathquill4quill/issues/17 for more context.
