### ISSUE TITLE
#Discussion how to add this MathQuill4Quill in react ?? 

### ISSUE THREAD

**Issue by vishnu0320** [c-w/mathquill4quill#56]
I can't understand `To integrate this module with react-quill` how to integrate into React web app, can you tell me in details . 
`const { mathquill4quill } = window;`
where I add this `mathquill4quill.js` file and what I do with this `window` word???

**Comment by c-w** [comment]
Hi @vishnu0320. Thanks for reaching out.

To integrate mathquill4quill with React, first add a reference to `mathquill4quill.js` to your application via a script tag. For example, if you're using [create-react-app](https://github.com/facebook/create-react-app) you could add `<script src="/path/to/mathquill4quill.js">` into the `<head>` section of the `public/index.html` file. The mathquill4quill library will then automatically set itself up on the [window global object](https://developer.mozilla.org/en-US/docs/Web/API/Window) (see [code](https://github.com/c-w/mathquill4quill/blob/ff1bb5a8a5ee7c379d2b95e98eecb51ed0ec1104/mathquill4quill.js#L3)). In your React component you can then get a reference to mathquill4quill via the window object using `const { mathquill4quill } = window` as mentioned in the documentation.

Hope this helps. Let me know if there's any additional information that you require.

**Comment by vishnu0320** [comment]
hi @c-w I already try this, it showing to me `TypeError: mathquill4quill is not a function`
![image](https://user-images.githubusercontent.com/60692033/92140848-43683d80-ee2f-11ea-940e-1816b031b506.png)

I add  `<script src="./mathquill4quill.js"></script>`  this line in `index.html` and `mathquill4quill.js` placed in public folder.

**Comment by c-w** [comment]
If you place the mathquill4quill JS and CSS files into the public folder, make sure that the location is correct once the React build completed. An easy way to achieve this is using the [PUBLIC_URL](https://create-react-app.dev/docs/using-the-public-folder/) directive like this:

```html
<head>
  <link rel="stylesheet" href="%PUBLIC_URL%/mathquill4quill.css" />
  <script src="%PUBLIC_URL%/mathquill4quill.js"></script>
</head>
```

**Comment by c-w** [comment]
Going to resolve this as I haven't heard back and I believe the above setup should fix your issue (at least it did for my React setup with `create-react-app`). Feel free to re-open if you require any further assistance on this matter!

**Comment by TheDarkStrix** [comment]
```
Uncaught TypeError: Cannot read property 'options' of undefined
    at areAllDependenciesMet (mathquill4quill.js:58)
    at enableMathQuillFormulaAuthoring (mathquill4quill.js:340)
```

My source Code : 
[https://pastebin.com/bDP84zcs](https://pastebin.com/bDP84zcs)

Screenshot of the error :  
[https://ibb.co/42w5sNn](https://ibb.co/42w5sNn)


Not sure what is wrong here , any insights to get this working is very much appreciated .
I am using NEXTJS

**Comment by TheDarkStrix** [comment]
> Going to resolve this as I haven't heard back and I believe the above setup should fix your issue (at least it did for my React setup with `create-react-app`). Feel free to re-open if you require any further assistance on this matter!

@c-w 
```

Uncaught TypeError: Cannot read property 'options' of undefined
    at areAllDependenciesMet (mathquill4quill.js:58)
    at enableMathQuillFormulaAuthoring (mathquill4quill.js:340)
```
My source Code :
https://pastebin.com/bDP84zcs

Screenshot of the error :
https://ibb.co/42w5sNn

Not sure what is wrong here , any insights to get this working is very much appreciated .
I am using NEXTJS

**Comment by c-w** [comment]
@TheDarkStrix It looks to me like the ref returned null which can be the case during some phases of the React lifecycle. Deferring the `enableMathQuillFormulaAuthoring` until the ref is fully available should solve the issue.

**Comment by c-w** [comment]
See also https://github.com/c-w/mathquill4quill/issues/72.

**Comment by thangnh91** [comment]
@TheDarkStrix I got the same issue with nextjs. The cause is the ref doesn't work with next/dynamic as discussed [here](https://github.com/vercel/next.js/issues/4957#issuecomment-413841689). So, based on that comment, I use Editor.jsx to wrap QuillEditor.jsx and use forwardRef to pass the ref from Editor to QuillEditor.

`Editor.jsx`

```jsx
import dynamic from 'next/dynamic';
import React from "react";

const QuillEditor = dynamic(
  () => import("../components/QuillEditor").then((mod) => mod.default),
  { ssr: false, loading: () => <p>Loading ...</p> }
);
const ForwardedRefComponent = React.forwardRef((props, ref) => (
  <QuillEditor {...props} forwardedRef={ref} />
))

/**
 * Convert html to markdown and vice-versa
 */
class Editor extends React.Component {
  constructor(props) {
    super(props);
    this.editorRef = React.createRef();
  }

  render() {
    return <ForwardedRefComponent ref={(el) => {this.editorRef = el}}/>;
  }
}

export default Editor;
```

`QuillEditor.jsx`

```jsx
import $ from "jquery";
import katex from "katex";
import "katex/dist/katex.min.css";
import "mathquill/build/mathquill.css";
import "mathquill4quill/mathquill4quill.css";
import React from "react";
import ReactQuill, { Quill } from "react-quill";
import "react-quill/dist/quill.snow.css";

// https://katex.org/
if (typeof window !== "undefined") {
  window.katex = katex;
  window.jQuery = window.$ = $;
  const mathquill4quill = require('mathquill4quill');
  require ("mathquill/build/mathquill.js");
}

const CUSTOM_OPERATORS = [
  ["\\pm", "\\pm"],
  ["\\sqrt{x}", "\\sqrt"],
  ["\\sqrt[3]{x}", "\\sqrt[3]{}"],
  ["\\sqrt[n]{x}", "\\nthroot"],
  ["\\frac{x}{y}", "\\frac"],
  ["\\sum^{s}_{x}{d}", "\\sum"],
  ["\\prod^{s}_{x}{d}", "\\prod"],
  ["\\coprod^{s}_{x}{d}", "\\coprod"],
  ["\\int^{s}_{x}{d}", "\\int"],
  ["\\binom{n}{k}", "\\binom"]
];

const CustomUndo = () => (
  <svg viewBox="0 0 18 18">
    <polygon className="ql-fill ql-stroke" points="6 10 4 12 2 10 6 10" />
    <path
      className="ql-stroke"
      d="M8.09,13.91A4.6,4.6,0,0,0,9,14,5,5,0,1,0,4,9"
    />
  </svg>
);

const CustomRedo = () => (
  <svg viewBox="0 0 18 18">
    <polygon className="ql-fill ql-stroke" points="12 10 14 12 16 10 12 10" />
    <path
      className="ql-stroke"
      d="M9.91,13.91A4.6,4.6,0,0,1,9,14a5,5,0,1,1,5-5"
    />
  </svg>
);

// Undo and redo functions for Custom Toolbar
function undoChange() {
  this.quill.history.undo();
}
function redoChange() {
  this.quill.history.redo();
}

// Modules object for setting up the Quill editor
export const modules = {
  formula: true,
  toolbar: {
    container: "#quillToolbar",
    handlers: {
      undo: undoChange,
      redo: redoChange,
    },
  },
  history: {
    delay: 500,
    maxStack: 100,
    userOnly: true,
  },
};

// Formats objects for setting up the Quill editor
// https://quilljs.com/docs/formats/
export const formats = [
  // Inline
  "background", // Background Color
  "bold", // Bold
  "color", // Color
  "font", // Font
  "code", // Inline Code
  "italic", // Italic
  "link", // Link
  "size", // Size
  "strike", // Strikethrough
  "script", // Superscript/Subscript
  "underline", // Underline

  // Block
  "blockquote", // Blockquote
  "header", // Header
  "indent", // Indent
  "list", // List
  "align", // Text Align
  "direction", // Text Direction
  "code-block", // Code Block

  // Embeds
  "formula", // Formula
  "image", // Image
  "video", // Video
];

// Quill Toolbar component
export const QuillToolbar = () => (
  <div id="quillToolbar">
    <span className="ql-formats">
      <select className="ql-size" defaultValue="normal">
        <option value="small">Small</option>
        <option value="normal">Normal</option>
        <option value="large">Large</option>
        <option value="huge">Huge</option>
      </select>
    </span>
    <span className="ql-formats">
      <button className="ql-bold" type="button" />
      <button className="ql-italic" type="button" />
      <button className="ql-underline" type="button" />
      <button className="ql-strike" type="button" />
    </span>
    <span className="ql-formats">
      <select className="ql-color" />
      <select className="ql-background" />
    </span>
    <span className="ql-formats">
      <button className="ql-script" value="sub" type="button" />
      <button className="ql-script" value="super" type="button" />
    </span>
    <span className="ql-formats">
      <button className="ql-header" value="1" type="button" />
      <button className="ql-header" value="2" type="button" />
      <button className="ql-blockquote" type="button" />
      <button className="ql-code-block" type="button" />
      <button className="ql-code" type="button">
        <CustomUndo />
      </button>
    </span>
    <span className="ql-formats">
      <button className="ql-list" value="ordered" type="button" />
      <button className="ql-list" value="bullet" type="button" />
      <button className="ql-indent" value="-1" type="button" />
      <button className="ql-indent" value="+1" type="button" />
    </span>
    <span className="ql-formats">
      <button className="ql-direction" value="rtl" type="button" />
      <select className="ql-align" />
    </span>
    <span className="ql-formats">
      <button className="ql-link" type="button" />
      <button className="ql-image" type="button" />
      <button className="ql-video" type="button" />
      <button className="ql-formula" type="button" />
    </span>
    <span className="ql-formats">
      <button className="ql-clean" type="button" />
    </span>
    <span className="ql-formats">
      <button className="ql-undo" type="button">
        <CustomUndo />
      </button>
      <button className="ql-redo" type="button">
        <CustomRedo />
      </button>
    </span>
  </div>
);

class QuillEditor extends React.Component {

  constructor(props) {
    super(props)
    this.quillRef = null;      // Quill instance
    this.reactQuillRef = null; // ReactQuill component
    this.attachQuillRefs = this.attachQuillRefs.bind(this);
  }

  componentDidMount() {
    this.attachQuillRefs()
  }
  
  componentDidUpdate() {
    this.attachQuillRefs()
  }

  attachQuillRefs = () => {
    if (typeof this.reactQuillRef.getEditor !== 'function') return;
    this.quillRef = this.reactQuillRef.getEditor();
    const enableMathQuillFormulaAuthoring = mathquill4quill({ Quill, katex });
    enableMathQuillFormulaAuthoring(
      this.quillRef,
      {operators: CUSTOM_OPERATORS}
    );
  }

  render() {
    return (
      <>
        <QuillToolbar />
        <ReactQuill
          ref={(el) => { this.reactQuillRef = el; console.log("ref", el) }}
          {...this.props}
          theme={this.props.theme || "snow"}
          placeholder={this.props.placeholder || "Compose an epic ..."}
          modules={modules}
          formats={formats}
          bounds={".quill"}
        />
      </>
    );
  }
}

export default QuillEditor;
```

**Comment by damarsimple** [comment]
@thangnh91 you saved my life

**Comment by thangnh91** [comment]
@damarsimple Sorry, there was a mistake here. The forward ref is not necessary, and the code doesn't work like that. Just use next/dynamic to dynamic import QuillEditor in Editor is enough, don't need forward ref.

`Editor.jsx`
```jsx
import dynamic from "next/dynamic";
import React from "react";

const QuillEditor = dynamic(
  () => import("./QuillEditor").then((mod) => mod.default),
  { ssr: false, loading: () => <p>Loading ...</p> }
);

class Editor extends React.Component {
  render() {
    return <QuillEditor />;
  }
}

export default Editor;
```

**Comment by c-w** [comment]
@thangnh91 Feel free to open a pull request to add the NextJS sample.

**Comment by damarsimple** [comment]
@thangnh91  its oke i figured it out myself based on your codes

this is my version using functional component

Editor.tsx
`
/* eslint-disable react/display-name */
import dynamic from "next/dynamic";
import { AiOutlineLoading } from "react-icons/ai";

export const Editor = dynamic(() => import("../components/MainEditor"), {
  ssr: false,
  loading: () => <AiOutlineLoading className="animate-spin" size="1.5em" />,
});
`


MainEditor.tsx
`//@ts-nocheck

import $ from "jquery";
import katex from "katex";

import React, { useEffect, useRef } from "react";
import ReactQuill, { Quill } from "react-quill";

// https://katex.org/
if (typeof window !== "undefined") {
  window.katex = katex;
  window.jQuery = window.$ = $;
  const mathquill4quill = require("mathquill4quill");
  require("mathquill/build/mathquill.js");
}

const CUSTOM_OPERATORS = [
  ["\\pm", "\\pm"],
  ["\\sqrt{x}", "\\sqrt"],
  ["\\sqrt[3]{x}", "\\sqrt[3]{}"],
  ["\\sqrt[n]{x}", "\\nthroot"],
  ["\\frac{x}{y}", "\\frac"],
  ["\\sum^{s}_{x}{d}", "\\sum"],
  ["\\prod^{s}_{x}{d}", "\\prod"],
  ["\\coprod^{s}_{x}{d}", "\\coprod"],
  ["\\int^{s}_{x}{d}", "\\int"],
  ["\\binom{n}{k}", "\\binom"],
];

const CustomUndo = () => (
  <svg viewBox="0 0 18 18">
    <polygon className="ql-fill ql-stroke" points="6 10 4 12 2 10 6 10" />
    <path
      className="ql-stroke"
      d="M8.09,13.91A4.6,4.6,0,0,0,9,14,5,5,0,1,0,4,9"
    />
  </svg>
);

const CustomRedo = () => (
  <svg viewBox="0 0 18 18">
    <polygon className="ql-fill ql-stroke" points="12 10 14 12 16 10 12 10" />
    <path
      className="ql-stroke"
      d="M9.91,13.91A4.6,4.6,0,0,1,9,14a5,5,0,1,1,5-5"
    />
  </svg>
);

// Undo and redo functions for Custom Toolbar
function undoChange() {
  this.quill.history.undo();
}
function redoChange() {
  this.quill.history.redo();
}

// Modules object for setting up the Quill editor
export const modules = {
  formula: true,
  toolbar: {
    container: "#quillToolbar",
    handlers: {
      undo: undoChange,
      redo: redoChange,
    },
  },
  history: {
    delay: 500,
    maxStack: 100,
    userOnly: true,
  },
};

// Formats objects for setting up the Quill editor
// https://quilljs.com/docs/formats/
export const formats = [
  // Inline
  "background", // Background Color
  "bold", // Bold
  "color", // Color
  "font", // Font
  "code", // Inline Code
  "italic", // Italic
  "link", // Link
  "size", // Size
  "strike", // Strikethrough
  "script", // Superscript/Subscript
  "underline", // Underline

  // Block
  "blockquote", // Blockquote
  "header", // Header
  "indent", // Indent
  "list", // List
  "align", // Text Align
  "direction", // Text Direction
  "code-block", // Code Block

  // Embeds
  "formula", // Formula
  //   "image", // Image
  //   "video", // Video
];

// Quill Toolbar component
export const QuillToolbar = () => (
  <div id="quillToolbar">
    <span className="ql-formats">
      <select className="ql-size" defaultValue="normal">
        <option value="small">Small</option>
        <option value="normal">Normal</option>
        <option value="large">Large</option>
        <option value="huge">Huge</option>
      </select>
    </span>
    <span className="ql-formats">
      <button className="ql-bold" type="button" />
      <button className="ql-italic" type="button" />
      <button className="ql-underline" type="button" />
      <button className="ql-strike" type="button" />
    </span>
    <span className="ql-formats">
      <select className="ql-color" />
      <select className="ql-background" />
    </span>
    <span className="ql-formats">
      <button className="ql-script" value="sub" type="button" />
      <button className="ql-script" value="super" type="button" />
    </span>
    <span className="ql-formats">
      <button className="ql-header" value="1" type="button" />
      <button className="ql-header" value="2" type="button" />
      <button className="ql-blockquote" type="button" />
      <button className="ql-code-block" type="button" />
      <button className="ql-code" type="button">
        <CustomUndo />
      </button>
    </span>
    <span className="ql-formats">
      <button className="ql-list" value="ordered" type="button" />
      <button className="ql-list" value="bullet" type="button" />
      <button className="ql-indent" value="-1" type="button" />
      <button className="ql-indent" value="+1" type="button" />
    </span>
    <span className="ql-formats">
      <button className="ql-direction" value="rtl" type="button" />
      <select className="ql-align" />
    </span>
    <span className="ql-formats">
      <button className="ql-link" type="button" />
      {/* <button className="ql-image" type="button" /> */}
      {/* <button className="ql-video" type="button" /> */}
      <button className="ql-formula" type="button" />
    </span>
    <span className="ql-formats">
      <button className="ql-clean" type="button" />
    </span>
    <span className="ql-formats">
      <button className="ql-undo" type="button">
        <CustomUndo />
      </button>
      <button className="ql-redo" type="button">
        <CustomRedo />
      </button>
    </span>
  </div>
);

export default function QTest({
  theme,
  placeholder,
  onChange,
  height,
}: {
  onChange: (e: string) => void;
  theme?: string;
  placeholder?: string;
  height?: number;
}) {
  const reactQuillRef = useRef(null);
  const attachQuillRefs = () => {
    if (typeof reactQuillRef.current?.getEditor !== "function") return;
    const enableMathQuillFormulaAuthoring = mathquill4quill({
      Quill,
      katex,
    });
    enableMathQuillFormulaAuthoring(reactQuillRef.current?.getEditor(), {
      operators: CUSTOM_OPERATORS,
      displayHistory: true,
    });
  };
  useEffect(() => {
    attachQuillRefs();
  }, [reactQuillRef]);

  return (
    <>
      <QuillToolbar />
      <ReactQuill
        style={{ height: height ?? 100 }}
        ref={reactQuillRef}
        theme={theme || "snow"}
        placeholder={placeholder || "Isi ...."}
        modules={modules}
        formats={formats}
        bounds={".quill"}
        onChange={onChange}
      />
    </>
  );
}
`

**Comment by thangnh91** [comment]
@damarsimple look awesome.
@c-w I created a pull request. 
P/s: Thanks for great tool.
