### ISSUE TITLE
Getting duplicate & weird displays

### ISSUE THREAD

**Issue by deepak-jha-kgp** [c-w/mathquill4quill#57]
While writing math equations, I'm getting both the formula and editable math field. On clicking save, shows up in the quill editor as following. Is this normal?
I'm using react-quill
![image](https://user-images.githubusercontent.com/40298030/93084356-89d05e80-f6b1-11ea-9116-17c45463a5f3.png)

Following is my code. Please help.
```import React from 'react';
import ReactQuill, { Quill } from 'react-quill';
const { mathquill4quill } = window;

export default class App extends React.Component {
  
  constructor(props) {
    super(props)
    this.state = { text: '' } // You can also pass a Quill Delta here
    this.handleChange = this.handleChange.bind(this)
    this.reactQuill = React.createRef();
  }
  handleChange(value) {
      console.log(value)
    this.setState({ text: value })
  }
  componentDidMount() {
    const enableMathQuillFormulaAuthoring = mathquill4quill({ Quill });
    enableMathQuillFormulaAuthoring(this.reactQuill.current.editor);
  }

  render() {
    return (
      <ReactQuill
        ref={this.reactQuill}
        value={this.state.text}
                  onChange={this.handleChange}
        modules={{
          formula: true,
          toolbar: [["formula", /* ... other toolbar items here ... */]]
         
        }}
    
      />   
    );
  }
}`

**Comment by c-w** [comment]
Thanks for reaching out. This looks like an odd issue. Could you confirm what versions of the CSS and JS files of Quill, MathQuill, KaTeX, and mathquill4quill you're using?

**Comment by deepak-jha-kgp** [comment]
Thanks @c-w I changed the css files to one served from cdn, no they seem to be working fine. Amazing library, thanks for this.

**Comment by c-w** [comment]
See also https://github.com/c-w/mathquill4quill/issues/72.
