### ISSUE TITLE
Is this available as npm package ?

### ISSUE THREAD

**Issue by rajparmar7879** [c-w/mathquill4quill#58]
PLease give your reply as earliest.

**Comment by c-w** [comment]
No, `mathquill4quill` currently isn't being published to NPM and as of version 2.1.2 it's also not set up as a module for usage with `require` or `import`. Official builds as well as minified assets can be found on the [releases page](https://github.com/c-w/mathquill4quill/releases) and it's recommended to integrate the JS and CSS files via script and style tags.

If this is a feature important to you, pull requests to make the package work with `require` are welcome and then I'll be happy to set up the infrastructure to publish to NPM.
