### ISSUE TITLE
Changing font size of formula in text editor

### ISSUE THREAD

**Issue by tariksubasi** [c-w/mathquill4quill#61]
Hi there. First of all thanks for this package.

My question is actually quiete clear. 
![asdasdasd](https://user-images.githubusercontent.com/27722465/99145340-ff8b8300-267e-11eb-89bc-f1d1ff21c098.JPG)

how can i change the font size of formulas? Couldn't find it. 

best regards.

**Comment by c-w** [comment]
If you're looking to customize the font in the formula editor, you can use the CSS selector `.mq-root-block`. To customize the rendered equations in the editor, you can use the CSS selector `.katex-html`.

**Comment by c-w** [comment]
Resolving. Feel free to re-open if you have any problems with the suggestion above.
