### ISSUE TITLE
enter formula pane modification

### ISSUE THREAD

**Issue by tariksubasi** [c-w/mathquill4quill#63]
![image](https://user-images.githubusercontent.com/27722465/99273737-7caf2780-283a-11eb-985b-a0a1148d6e24.png)
Hi there. Is there any way to modify this pane? I want to add tabs to this suggestion screen? Could you please help me how to do it?

**Comment by c-w** [comment]
You can use the CSS selectors `.mathquill4quill-operator-container` and `.mathquill4quill-operator-button` to target the button group and individual buttons for styling. If you need more complex logic that can't be expressed in plain CSS, you could use a [MutationObserver](https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver) to check when the formula editor popup appears, i.e. when `.ql-hidden` is removed from `.ql-tooltip` and apply your custom transformations via Javascript in the observer's callback.

**Comment by c-w** [comment]
Resolving. Feel free to re-open if you have any problems with the suggestion above
