### ISSUE TITLE
Equation button on tab page

### ISSUE THREAD

**Issue by purnomosejati** [c-w/mathquill4quill#64]
![mathquill](https://user-images.githubusercontent.com/6489443/100613220-c32a7900-3346-11eb-90d6-afe4ba23de71.png)

Hi Wolff,

I was able to add more equation and symbol to mathquill4quill toolbar as shown here. However, if I add some more, it will expand div both vertical and horizontal.

Can I ask how to put them into pages with tab so it can be categorized.

Regards

**Comment by c-w** [comment]
There was a similar question about tabs for the operator buttons in https://github.com/c-w/mathquill4quill/issues/63 so I would suggest taking a look at the discussion over there. Currently there is no support for tabs in this project, however I'd gladly accept pull requests to implement the feature.

**Comment by c-w** [comment]
Resolving. Feel free to re-open if you have any problems with the suggestion above.
