### ISSUE TITLE
Load MathQuill and Katex to React application

### ISSUE THREAD

**Issue by quanphan2906** [c-w/mathquill4quill#66]
Can you provide further guidance on how one may add MathQuill and Katex to their React application prior to enabling the mathquill formula editor on the ReactQuill component, as suggested in the doc: 

> To integrate this module with react-quill, add references to the JS and CSS files of MathQuill and KaTeX to your application

**Comment by c-w** [comment]
MathQuill has a section in their documentation on how to include the library, see ["Download and Load" in "Getting Started"](http://docs.mathquill.com/en/latest/Getting_Started/#download-and-load).
Alternatively, refer to the [mathquill4quill demo page implementation](https://github.com/c-w/mathquill4quill/blob/cd636f8c6cd814bc19d6c2ca3567c6b2c45fa34d/index.html#L8-L10).

KaTeX also has a section in their documentation on how to include the library, see ["Starter template" in "Installation > Browser"](https://katex.org/docs/browser.html#starter-template).
Alternatively, refer to the [mathquill4quill demo page implementation](https://github.com/c-w/mathquill4quill/blob/cd636f8c6cd814bc19d6c2ca3567c6b2c45fa34d/index.html#L16-L19).

**Comment by c-w** [comment]
I updated the README to include the dependency setup links also in the React section (see https://github.com/c-w/mathquill4quill/commit/39ed6423beff42518fa8e01b22237739461c3c03).

Resolving, feel free to reopen if you have any further questions.

**Comment by c-w** [comment]
See also https://github.com/c-w/mathquill4quill/issues/72.
