### ISSUE TITLE
React: Formula module requires KaTeX

### ISSUE THREAD

**Issue by lugotal** [c-w/mathquill4quill#68]
Hi,

I'm trying to use mathquill4quill within a component in an existing react application. I installed react-quill and KaTeX dependencies but I am getting this error when using the component:
![grafik](https://user-images.githubusercontent.com/9104054/108357774-2dd4ad80-71ee-11eb-8371-a40654f589f8.png)

My imports look like this:
`import 'katex/dist/katex.min.css'`
`import katex from 'katex'`
`import ReactQuill, { Quill } from 'react-quill'`
`import 'mathquill4quill/mathquill4quill.css'`
`import mathquill4quill from 'mathquill4quill'`

I also attempted this:
`const enableMathQuillFormulaAuthoring = mathquill4quill({ Quill, katex })`

But this didn't help. Are there any further instructions on how to utilize mathquill4quill? Preferably without adding dependencies to the html page containing the react application.

Thanks!

**Comment by c-w** [comment]
Thanks for reaching out @lugotal. It looks to me like that stack-trace originates inside of ReactQuill as opposed to mathquill4quill. As per the discussion in https://github.com/zenoamaro/react-quill/issues/325 I would suggest to make katex globally available by adding `window.katex = katex` after your import statements.

**Comment by lugotal** [comment]
Ah, that did it. Thank you very much!
I did not realize that it was an issue with React-Quill itself, I apologize.
