### ISSUE TITLE
Issue with top spacing on operator buttons

### ISSUE THREAD

**Issue by boomanaiden154** [c-w/mathquill4quill#7]
With certain latex expressions inside the operator buttons, the spacing on the top of the button gets offset. I have currently observed this behavior with `\frac`, and there may be other latex commands that impact this, but I have not tested this thoroughly(maybe automated testing is on the roadmap?). 
![Screenshot_20190615_155036](https://user-images.githubusercontent.com/39388941/59557192-a5b5f380-8f88-11e9-9763-7f993ac2a79c.png)
The planned fix for this which I am working on in my fork is to place all of the buttons in a `div` with its style attribute set to `position:relative`, and then add a style attribute to all the operator buttons of `position:absolute;top:0px;`

**Comment by boomanaiden154** [comment]
Using `position:absolute` breaks the flow, but using `display:flex;` works well.

**Comment by c-w** [comment]
Resolves in https://github.com/c-w/mathquill4quill/pull/8.

**Comment by c-w** [comment]
Released in [v0.0.3](https://github.com/c-w/mathquill4quill/releases/tag/v0.0.3).
