### ISSUE TITLE
Advanced Katex features: mathfrak?

### ISSUE THREAD

**Issue by lakesare** [c-w/mathquill4quill#70]
Standard Quill formula extension allows us to input advanced katex formulas, e.g. `\mathfrak{X}` properly renders (see https://www.memcode.com/contact for a demo):

<img src="https://user-images.githubusercontent.com/7578559/113597916-d41d2b00-9655-11eb-9d78-0c3fac09ce8b.png" width="300"/>

This wouldn't work on https://justamouse.com/mathquill4quill:
<img src="https://user-images.githubusercontent.com/7578559/113598062-0595f680-9656-11eb-95d3-7427b5d1d64c.png" width="300"/>

Is it possible to enable advanced formulas in mathquill4quill?

**Comment by ahmed2m** [comment]
I think this one might be a problem in the upstream mathquill

**Comment by c-w** [comment]
As Ahmed mentioned, this is an upstream issue, see: https://github.com/mathquill/mathquill/issues/200
