### ISSUE TITLE
Change a formula after saving

### ISSUE THREAD

**Issue by kroehne** [c-w/mathquill4quill#71]
This is really great addition to quill and a nice example of using mathquill. Would it be possible to extend the extension so that you can edit formulas after finalizing them in the editor with "Save"? This doesn't seem to work in the demo, i.e. once the formula is saved, the user can only delete and re-enter the complete formula to change a formula, correct? Thanks and best regards!

**Comment by c-w** [comment]
Thanks for the suggestion. Editing formulae isn't supported in Quill currently so there's not much we can do in this extension unfortunately. See https://github.com/c-w/mathquill4quill/issues/54 and https://github.com/c-w/mathquill4quill/issues/17 for more context.
