### ISSUE TITLE
mathquill4quill does not detect ngx-quill on angular

### ISSUE THREAD

**Issue by robertvb** [c-w/mathquill4quill#75]
Hi all,

I was trying to follow https://github.com/c-w/mathquill4quill/issues/55 approach but is not working for me. 

I am getting: 

`mathquill4quill.js:48 Quill.js not loaded`

but quill editor is being loaded and perfectly rendered. 

I am using quill directly from my angular html template like:

`<quill-editor (onEditorCreated)="onEditorCreated($event)">...</quill-editor>`

Am I missing something? 

Thank you,

**Comment by robertvb** [comment]
Fixed adding needed dependencies to window

**Comment by c-w** [comment]
Glad you were able to resolve the issue. If you'd like to create a sample integration/app for Angular, the PR would be very welcome!
