### ISSUE TITLE
How to add matrix as CUSTOM_OPERATORS

### ISSUE THREAD

**Issue by wisnercelucus** [c-w/mathquill4quill#76]
Hi Team,

Please forgive my ignorance. 

I am integrating the tool with Angular. I have successfully integrated it with ngx-quill and Katex. It works great. Now, I need to add other CUSTOM_OPERATORS like matrices. I am very ignorant in LaTex, Tex in general. Can you give me some directive to integrate Matrices on various forms in the CUSTOM_OPERATORS?

Following the list, I copied from the example with react you provided.

`      const CUSTOM_OPERATORS = [
        ["\\pm", "\\pm"],
        ["\\sqrt{x}", "\\sqrt"],
        ["\\sqrt[3]{x}", "\\sqrt[3]{}"],
        ["\\sqrt[n]{x}", "\\nthroot"],
        ["\\frac{x}{y}", "\\frac"],
        ["\\sum^{s}_{x}{d}", "\\sum"],
        ["\\prod^{s}_{x}{d}", "\\prod"],
        ["\\coprod^{s}_{x}{d}", "\\coprod"],
        ["\\int^{s}_{x}{d}", "\\int"],
        ["\\binom{n}{k}", "\\binom"],
        []
      ];`

**Comment by c-w** [comment]
Thanks for reaching out. Refer to this past conversation for matrices: https://github.com/c-w/mathquill4quill/issues/52.

**Comment by c-w** [comment]
Closing. Feel free to reopen if you have any further questions.
