### ISSUE TITLE
Unable to edit formula on Mobile

### ISSUE THREAD

**Issue by barman47** [c-w/mathquill4quill#82]
While using mathquill4quill on a mobile device, it is not possible to delete or edit the Formula once it's created. Technically you can't even highlight it. Trying to delete it dismisses the keyboard. The issue also occurs [here](https://justamouse.com/mathquill4quill/) on the live demo.

**Comment by c-w** [comment]
Thanks for reaching out. Editing a formula isn't supported in Quill currently so there's not much we can do in this extension unfortunately. See #80, #71, #54 and #17 for more context.

**Comment by barman47** [comment]
Thanks for your feedback!
