### ISSUE TITLE
Support table in the editor

### ISSUE THREAD

**Issue by ultrainstinct1987** [c-w/mathquill4quill#84]
Hi,
This project is amazing but will it be possible to support table as well in the editor?

**Comment by c-w** [comment]
Could you be more specific by what you mean by table support? This project just concerns itself with the math/function plugin for Quill. Perhaps your question is better suited for the upstream [QuillJS project](https://github.com/quilljs/quill)?

**Comment by ultrainstinct1987** [comment]
What I meant is under toolbar, allow the insertion of table for better alignment.

**Comment by c-w** [comment]
Thanks for the additional detail. That would be a request for the upstream QuillJS project. The scope of this here project is only to improve the editing experience in the math editor of QuillJS. Take a look at this discussion about tables in QuillJS: https://github.com/quilljs/quill/issues/117
