### ISSUE TITLE
Is this deliberate Or a bug? 

### ISSUE THREAD

**Issue by ultrainstinct1987** [c-w/mathquill4quill#85]
Hi, I manage to figure out quite abit of stuff on this mathquill4quill. 

i have the last question to ask if anyone can answer. 
When typing \displaystyle\sum it was displaying summation with text above and below the summation in the mini textbook. 

However, when I click save, the text appear next to summation sign instead. 
Is there anyway which I can fixed it?

**Comment by c-w** [comment]
So the preview uses [katex](https://katex.org/) for rendering but the editor uses [mathquill](http://mathquill.com/) to display the math after it's been entered. Could you check if the formula you're writing renders differently on these two libraries? There are preview widgets on each of the linked project pages.

**Comment by ultrainstinct1987** [comment]
I think the main issue is that the preview uses
\displaystyle\sum where as once it get input into the editor, it become \sum or \textstyle\sum

**Comment by c-w** [comment]
So it looks like MathQuill doesn't support `\displaystyle`, see https://github.com/mathquill/mathquill/issues/589. As such, there's not much we can do in this project as QuillJS depends on MathQuill.

**Comment by ultrainstinct1987** [comment]
> So it looks like MathQuill doesn't support `\displaystyle`, see [mathquill/mathquill#589](https://github.com/mathquill/mathquill/issues/589). As such, there's not much we can do in this project as QuillJS depends on MathQuill.

MathQuill does support display style for summation. 
but when it is save into QuillJS, it become textstyle 

I managed to fix it by checking if latex contain \sum and replace the latex by \displaystyle\sum. 

![Uploading A987AB20-7AF7-4804-96F7-B413493E51F6.jpeg…]()

**Comment by ultrainstinct1987** [comment]
![0879DE06-1DF6-4F1B-866D-10BB1762EF09](https://user-images.githubusercontent.com/102927718/164986167-ede7f8cb-54a7-4684-9b0e-736ab23df7b6.jpeg)
![56556654-9083-4708-9039-68FD663CA895](https://user-images.githubusercontent.com/102927718/164986172-a40ea61b-1195-4686-980a-b57f69f8249c.jpeg)
