### ISSUE TITLE
Is there a way to modify the latex before inserting into the textarea?

### ISSUE THREAD

**Issue by ultrainstinct1987** [c-w/mathquill4quill#86]
Hi, if I want to modify the latex input beside the save button before mathquill4quill insert into textarea, where can I insert the code at? 

I try to insert coding at the save button but I am unable to modify the input.

**Comment by c-w** [comment]
You can see how the library synchronizes the LaTeX input with MathQuill [here](https://github.com/c-w/mathquill4quill/blob/4975e0776e3de2f68562d3296cde9bde255dc1a3/mathquill4quill.js#L136-L138). I think the simplest way to achieve what you're looking for would be to modify the code to respect an existing `edit` handler, something like this:

```diff
          edit() {
+           if (handlers.edit) {
+             handlers.edit();
+           }
            const latex = mqField.latex();
            latexInput.value = latex;
            setCacheItem(cacheKey, latex);
          },
```

And then when you set up your MathQuill instance you'd provide your custom edit handler implementation which can grab a reference to the `latexInput` and modify it as you require.

**Comment by ultrainstinct1987** [comment]
Hi, thanks for the reply. I will only want to edit the latex only when the user click on save. 
May I know where can I modify the input latex before it get transfer to quill?

**Comment by ultrainstinct1987** [comment]
May I know which variable do I send the EDITED latex to? 
I try using latexInput.value = editedLatex; 
It seem to just update the uneditedLatex into Quill

**Comment by c-w** [comment]
`latextInput.value` is the right place, I suspect you're seeing a sequencing issue with the order of calls.

**Comment by ultrainstinct1987** [comment]
Do you know where exactly is part of the code that is responsible for inserting mathquill into quill. I only saw those 2 functions.

addItemToHistoryList(cacheKey);
removeCacheItem(cacheKey);

**Comment by ultrainstinct1987** [comment]
> `latextInput.value` is the right place, I suspect you're seeing a sequencing issue with the order of calls.

Is there any solution to sequence the correct call?

**Comment by c-w** [comment]
On edit, we synchronize the fields [here](https://github.com/c-w/mathquill4quill/blob/4975e0776e3de2f68562d3296cde9bde255dc1a3/mathquill4quill.js#L136-L140). The actual saving is the handled by upstream QuillJS. Maybe there's a handler (like [enter here](https://github.com/c-w/mathquill4quill/blob/4975e0776e3de2f68562d3296cde9bde255dc1a3/mathquill4quill.js#L141-L143)) that will do what you want.

**Comment by ultrainstinct1987** [comment]
Hi, I have tried inputting function there but it still insert the old latex into Quill. 
Is there any other handler that I can try?

What I am trying to do is that I am trying to replace \frac with \dfrac before it get insert into quilljs after the user clicked on save.

**Comment by ultrainstinct1987** [comment]
Hi, I managed to fix it using a workaround for the edit() function call. Thanks.

**Comment by c-w** [comment]
Great! Could you post your solution here also as a future reference for others? Thanks!

**Comment by ultrainstinct1987** [comment]
Sure. 

Below are the code I used.

>  function findClosingBracket(str, pos) {
    const rExp = /\{|\}/g;
    rExp.lastIndex = pos + 1;
    var deep = 1;
    while ((pos = rExp.exec(str))) {
      if (!(deep += str[pos.index] === "{" ? 1 : -1 )) { return pos.index }
    }
  }  

>  function convertFrac(latex,delimiter){
        const stringArray = latex.split(delimiter);
           for (i = 0; i < stringArray.length-1; i++) {
                  var position = findClosingBracket(stringArray[i+1],0);
                  var part1 = stringArray[i+1].slice(0,position+1);
                  console.log("part1 : "+JSON.stringify(part1));
                  const part2 = stringArray[i+1].slice(position+1);
                  console.log("part2 : "+part2);
                  part1 = part1.replaceAll("\\dfrac","\\frac");
                  stringArray[i+1]=part1+part2;            
          } 
          console.log("Process : "+stringArray.join(delimiter));
        return stringArray.join(delimiter);
  }

         edit() {
            var latex = mqField.latex();
            latex = latex.replaceAll("frac","dfrac");
            if(latex.match("\sum")){
              latexInput.value = "\\displaystyle"+latex;
            }else if(latex.match("\lim")){
              latexInput.value=latex.replaceAll("\\lim","\\lim\\limits");  
            }else if(latex.indexOf("^") > 0 || latex.indexOf("_") > 0){
               if(latex.indexOf("^")>0){
                latex = convertFrac(latex,"^"); 
               }
               if(latex.indexOf("_")>0){
                latex = convertFrac(latex,"_"); 
               }
              latexInput.value = latex;
            }  
            else{
              latexInput.value = latex;
            }
          }
>
