### ISSUE TITLE
Non commands as button values issue

### ISSUE THREAD

**Issue by nesh325** [c-w/mathquill4quill#87]
Looked at this previous issue - #39 

<strike>
The proposed solution at the end that was merged does not work properly. 

For example ['\\dot{a}', '\\dot{a}'] only works with myField.cmd instead of myField.write and the {a} needs to be on both otherwise it doesn't print anything. But doing so you can't edit what's in the curly brackets

This is what prints out in the text area - It doesn't convert to a preview either 

![Screen Shot 2022-08-04 at 17 32 25 PM](https://user-images.githubusercontent.com/70300148/182956644-9924d0b4-9b81-4f25-9e03-cb978212d450.png)

This is what the output is when it's saved which is correct 

![Screen Shot 2022-08-04 at 19 15 15 PM](https://user-images.githubusercontent.com/70300148/182970765-623ff385-ec9c-4544-a151-f648065802d3.png)
</strike>

Further testing done and found that React version works differently than the regular Javascript/HTML version. This seems to be the main issue in why it's not rendering the commands properly. 

React  - https://justamouse.com/mathquill4quill/reactjs/

Typing '\\dot' and then hitting enter returns just 'dot'

HTML/Javascript - https://justamouse.com/mathquill4quill/

Typing the above and hitting enter displays the the actual output with curser set to below the dot where you can enter a character 

Tested on Javascript/HTML version and the non command button works just fine 
![Screen Shot 2022-08-05 at 04 22 56 AM](https://user-images.githubusercontent.com/70300148/183035318-07d07f17-bd1e-4853-97d8-7e0b74531675.png)

**Comment by c-w** [comment]
Apologies for not following up on this, somehow the notification for the issue slipped through the cracks. In any case, I believe this isn't a bug but an issue with differing versions of katex and mathquill used across the two demo environments. I'm pushing a fix to align the versions so that the `\dot` command will work across all of them.

**Comment by c-w** [comment]
The fix for this has been released to the demo pages:

<img width="649" alt="Screenshot of reactjs demo" src="https://user-images.githubusercontent.com/1086421/194732051-6aa5df96-a594-458a-be26-a5c1c3179e14.png">
