### ISSUE TITLE
Formula module not enabled

### ISSUE THREAD

**Issue by lucasbbsdk** [c-w/mathquill4quill#88]
Hello,

I want the editor with these nice addons you game us, but I am not able to get this running

Everytime I try to run your editor I get the following error: ```Formula module not enabled```

This is related to this piece of your code:

`            if (!quill.options.modules.formula) {
                console.log(quill.options.modules.formula, 'Formula module not enabled') // eslint-disable-line no-console
                return false
            }`

can you help me please?

**Comment by c-w** [comment]
Which versions of packages (quill/mathquill4quill) are you using?

**Comment by lucasbbsdk** [comment]
I am using react-quill version 1.3.5 and mathquill4quill version 2.3.0

**Comment by lucasbbsdk** [comment]
I already managed to resolve my problem, thank you

**Comment by c-w** [comment]
Could you share the solution here for others who may have the same issue in the future?

**Comment by lucasbbsdk** [comment]
Ok, I am not sure if that was the case, however the order o the import statements is very important...
It just started working here after I've used those eslin rules here:

```/* eslint-disable import/first */
/* eslint-disable  simple-import-sort/sort */```

I mean the order on which the import statements are presented in the Editor.js file from the react example.

I would like also to make a suggestion

What if there was a way to erase a formula from history? It could be utile

**Comment by c-w** [comment]
That sounds like a useful feature. Feel free to open a PR for it and I’m happy to review.
