### ISSUE TITLE
[feature request] Same feature for react-quill

### ISSUE THREAD

**Issue by amaslakov** [c-w/mathquill4quill#9]
It's actually not a feature request ) but could you please help integrate the same feature in react-quill?

**Comment by c-w** [comment]
Thanks for reaching out @amaslakov. Hooking up this library with react-quill seems to be pretty straight forward. Could you please take a look at the modifications in https://github.com/c-w/mathquill4quill/pull/10 and let me know if this suits your use-cases?

**Comment by c-w** [comment]
Released in [v0.1.0](https://github.com/c-w/mathquill4quill/releases/tag/v0.1.0).

**Comment by amaslakov** [comment]
@c-w Works great, thank you! I noticed that the formula input doesn't get focused by default. Is it some side effect or that can be fixed some way?

**Comment by c-w** [comment]
Looks like this behavior also exists in the non-React version so I created a new issue for it: https://github.com/c-w/mathquill4quill/issues/12.
