### ISSUE TITLE
support onBlur event handler

### ISSUE THREAD

**Issue by VeraZab** [c-w/mathquill4quill#94]
Hi, thanks for the great work on mathquill4quill. I'm curious if there is already a way that I could support calling a custom function on the blur event of the mathquill input field. From reading the code, it doesn't seem like it. I see that there's [mathQuillConfig](https://github.com/c-w/mathquill4quill/issues/37) that supports [different cursor events](https://docs.mathquill.com/en/latest/Config/#outof-handlers), but I don't think that any of those would be the same as an onBlur event.

Would you accept a pr that adds this functionality ? I'd like to attempt it. Thanks!

**Comment by c-w** [comment]
Yes, PRs welcome :+1:
